all:
  vars:
    ansible_user: "admin"
    ansible_password:
    switch_password:
    ansible_python_interpreter: python
    ansible_httpapi_validate_certs: false
    ansible_httpapi_use_ssl: true
    ansible_httpapi_login_domain: "local"
  children:
    ndfc:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: cisco.dcnm.dcnm
      hosts:

